version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ktor_postgres
    environment:
      POSTGRES_USER: ktor_user
      POSTGRES_PASSWORD: ktor_password
      POSTGRES_DB: ktor_tutorial_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ktor_user -d ktor_tutorial_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: ktor_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data: